# yaml-language-server: $schema=https://raw.githubusercontent.com/Ventairy/ship-my-flutter/main/schemas/config.schema.json

schema_version: 1
app_path: .
target_branch: main
release_branch_prefix: ship-my-flutter
hooks: {}
platforms:
  ios:
    enabled: true
    initial_version: 1.0.0
    bundle_id: "com.example.shipmyfluttere2e"
    testflight:
      groups: []
      wait_timeout_minutes: 45
    app_store:
      mode: upload
